#!/bin/bash
#
# generate_sdk_projects.sh
#
# Generates per-oscillator SDK project directories under
# logue-sdk/platform/drumlogue/ for the official Docker build system.
#
# Each project directory contains:
#   - Makefile   (copy of SDK dummy-synth/Makefile)
#   - config.mk  (project-specific sources, includes, and defines)
#
# Usage: ./generate_sdk_projects.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDK_DRUMLOGUE="${SCRIPT_DIR}/logue-sdk/platform/drumlogue"
SDK_MAKEFILE="${SDK_DRUMLOGUE}/dummy-synth/Makefile"

# Verify SDK Makefile exists
if [ ! -f "$SDK_MAKEFILE" ]; then
    echo "ERROR: SDK Makefile not found at $SDK_MAKEFILE"
    echo "Make sure logue-sdk submodule is initialized and on the main branch."
    exit 1
fi

# Path from project dir back to repo root: ../../../../
PROJROOT='$$(PROJROOT)'
# (We use $$ in heredocs to produce a literal $ for Make variables)

##############################################################################
# Helper: create one project directory
#
# Usage: create_project <dir_name> <project_name>
#                       <osc_source> <engine_sources> <udefs> <block_size>
#
# engine_sources: space-separated list (without PROJROOT prefix)
# udefs: compiler defines (e.g., "-DOSC_VA")
##############################################################################
create_project() {
    local dir_name="$1"
    local project_name="$2"
    local osc_source="$3"    # e.g., "macro-oscillator2.cc" or "modal-strike.cc"
    local engine_sources="$4" # space-separated engine .cc files
    local udefs="$5"
    local block_size="$6"

    local project_dir="${SDK_DRUMLOGUE}/${dir_name}"

    echo "Creating project: ${dir_name} (${project_name})"

    # Create directory
    mkdir -p "$project_dir"

    # Copy SDK Makefile
    cp "$SDK_MAKEFILE" "${project_dir}/Makefile"

    # Generate config.mk
    cat > "${project_dir}/config.mk" << CONFIGEOF
##############################################################################
# SDK project configuration for ${project_name}
#
# Generated by generate_sdk_projects.sh
# For use with logue-sdk Docker build system.
##############################################################################

PROJECT := ${project_name}
PROJECT_TYPE := synth

# Path back to eurorack-prologue repo root
PROJROOT := ../../../..

##############################################################################
# Sources
#

# C sources (unit header)
CSRC = \$(PROJROOT)/header.c

# C++ sources (drumlogue wrapper + adapter + oscillator + engine)
CXXSRC  = \$(PROJROOT)/drumlogue_unit_wrapper.cc
CXXSRC += \$(PROJROOT)/drumlogue_osc_adapter.cc
CXXSRC += \$(PROJROOT)/${osc_source}
CONFIGEOF

    # Append engine sources
    for src in $engine_sources; do
        echo "CXXSRC += \$(PROJROOT)/${src}" >> "${project_dir}/config.mk"
    done

    # Append remaining config
    cat >> "${project_dir}/config.mk" << CONFIGEOF

##############################################################################
# Include paths
#
# - drumlogue/   : userosc.h compatibility header
# - eurorack/    : Mutable Instruments source headers
# - repo root    : drumlogue_osc_adapter.h
#
# SDK common/ headers (runtime.h, unit.h, attributes.h) are added
# automatically by the SDK Makefile via DINCDIR.
#

UINCDIR  = \$(PROJROOT)/drumlogue
UINCDIR += \$(PROJROOT)/eurorack
UINCDIR += \$(PROJROOT)

##############################################################################
# Libraries
#

ULIBDIR =

ULIBS  = -lm
ULIBS += -lc

##############################################################################
# Defines
#

UDEFS  = ${udefs}
UDEFS += -DOSC_NATIVE_BLOCK_SIZE=${block_size}
CONFIGEOF

    echo "  -> Created ${project_dir}/config.mk"
}

##############################################################################
# Plaits-based oscillators (macro-oscillator2.cc, block size 24)
##############################################################################

# Virtual Analog
create_project "mo2_va" "mo2_va" \
    "macro-oscillator2.cc" \
    "eurorack/plaits/dsp/engine/virtual_analog_engine.cc eurorack/stmlib/dsp/units.cc" \
    "-DOSC_VA" 24

# Waveshaping
create_project "mo2_wsh" "mo2_wsh" \
    "macro-oscillator2.cc" \
    "eurorack/plaits/dsp/engine/waveshaping_engine.cc eurorack/plaits/resources.cc eurorack/stmlib/dsp/units.cc" \
    "-DOSC_WSH" 24

# FM
create_project "mo2_fm" "mo2_fm" \
    "macro-oscillator2.cc" \
    "eurorack/plaits/dsp/engine/fm_engine.cc eurorack/plaits/resources.cc eurorack/stmlib/dsp/units.cc" \
    "-DOSC_FM" 24

# Grain
create_project "mo2_grn" "mo2_grn" \
    "macro-oscillator2.cc" \
    "eurorack/plaits/dsp/engine/grain_engine.cc eurorack/plaits/resources.cc eurorack/stmlib/dsp/units.cc" \
    "-DOSC_GRN" 24

# Additive
create_project "mo2_add" "mo2_add" \
    "macro-oscillator2.cc" \
    "eurorack/plaits/dsp/engine/additive_engine.cc eurorack/plaits/resources.cc eurorack/stmlib/dsp/units.cc" \
    "-DOSC_ADD" 24

# String
create_project "mo2_string" "mo2_string" \
    "macro-oscillator2.cc" \
    "eurorack/plaits/dsp/engine/string_engine.cc eurorack/plaits/dsp/physical_modelling/string_voice.cc eurorack/plaits/dsp/physical_modelling/string.cc eurorack/plaits/resources.cc eurorack/stmlib/dsp/units.cc eurorack/stmlib/utils/random.cc" \
    "-DOSC_STRING" 24

# Wavetable A-F
for variant in a b c d e f; do
    upper=$(echo "$variant" | tr '[:lower:]' '[:upper:]')
    create_project "mo2_wt${variant}" "mo2_wt${variant}" \
        "macro-oscillator2.cc" \
        "eurorack/plaits/dsp/engine/wavetable_engine.cc eurorack/plaits/resources.cc eurorack/stmlib/dsp/units.cc" \
        "-DOSC_WT${upper}" 24
done

##############################################################################
# Elements-based oscillators (modal-strike.cc, block size 32)
##############################################################################

ELEMENTS_SOURCES="eurorack/elements/dsp/exciter.cc eurorack/elements/dsp/resonator.cc eurorack/elements/dsp/tube.cc eurorack/elements/dsp/string.cc eurorack/elements/dsp/multistage_envelope.cc eurorack/elements/resources.cc eurorack/stmlib/dsp/units.cc eurorack/stmlib/utils/random.cc"

# Modal Strike (24 modes, with limiter)
create_project "modal_strike" "modal_strike" \
    "modal-strike.cc" \
    "$ELEMENTS_SOURCES" \
    "-DELEMENTS_RESONATOR_MODES=24 -DUSE_LIMITER" 32

# Modal Strike 16 (no limiter)
create_project "modal_strike_16_nolimit" "modal_strike_16_nolimit" \
    "modal-strike.cc" \
    "$ELEMENTS_SOURCES" \
    "-DELEMENTS_RESONATOR_MODES=16" 32

# Modal Strike 24 (no limiter)
create_project "modal_strike_24_nolimit" "modal_strike_24_nolimit" \
    "modal-strike.cc" \
    "$ELEMENTS_SOURCES" \
    "-DELEMENTS_RESONATOR_MODES=24" 32

echo ""
echo "Done! Created 15 SDK project directories under:"
echo "  ${SDK_DRUMLOGUE}/"
echo ""
echo "To build with Docker:"
echo "  cd logue-sdk"
echo "  docker/run_cmd.sh build drumlogue/<project_name>"
echo ""
echo "For example:"
echo "  docker/run_cmd.sh build drumlogue/mo2_va"
