##############################################################################
# SDK project configuration for clouds_fx (CloudsFX delay/insert effect)
#
# Generated by generate_sdk_projects.sh
# For use with logue-sdk Docker build system.
#
# Unlike the synth Clouds project, CloudsFX is a delfx unit: it processes
# the FX-bus audio input.  It therefore uses the dedicated delfx wrapper
# (drumlogue_delfx_wrapper.cc) + clouds-fx.cc, and does NOT use the mono,
# output-only OSC adapter or the synth wrapper.
##############################################################################

PROJECT := clouds_fx
PROJECT_TYPE := delfx

# Path back to eurorack-prologue repo root
# (from drumlogue/<project>/ up two levels to repo root)
PROJROOT = ../..

# Override SDK Makefile defaults (see clouds/config.mk for rationale).
COMMON_INC_PATH = $(PROJROOT)/logue-sdk/platform/drumlogue/common
COMMON_SRC_PATH = $(PROJROOT)/logue-sdk/platform/drumlogue/common

##############################################################################
# Sources
#

# C sources (unit header)
CSRC = $(PROJROOT)/header.c

# C++ sources (delfx wrapper + FX engine glue + Clouds DSP engine)
CXXSRC  = $(PROJROOT)/drumlogue_delfx_wrapper.cc
CXXSRC += $(PROJROOT)/clouds-fx.cc
CXXSRC += $(PROJROOT)/eurorack-opt/clouds/dsp/granular_processor.cc
CXXSRC += $(PROJROOT)/eurorack/clouds/dsp/correlator.cc
CXXSRC += $(PROJROOT)/eurorack/clouds/dsp/mu_law.cc
CXXSRC += $(PROJROOT)/eurorack-opt/clouds/dsp/pvoc/phase_vocoder.cc
CXXSRC += $(PROJROOT)/eurorack/clouds/dsp/pvoc/frame_transformation.cc
CXXSRC += $(PROJROOT)/eurorack/clouds/dsp/pvoc/stft.cc
CXXSRC += $(PROJROOT)/eurorack/clouds/resources.cc
CXXSRC += $(PROJROOT)/eurorack/stmlib/dsp/units.cc
CXXSRC += $(PROJROOT)/eurorack/stmlib/dsp/atan.cc
CXXSRC += $(PROJROOT)/eurorack/stmlib/utils/random.cc

##############################################################################
# Include paths
#
# eurorack-opt/ MUST precede eurorack/: it shadows some of the submodule's
# headers and they change sizeof(GranularProcessor).
#

UINCDIR  = $(PROJROOT)/drumlogue
UINCDIR += $(PROJROOT)/eurorack-opt
UINCDIR += $(PROJROOT)/eurorack
UINCDIR += $(PROJROOT)
UINCDIR += $(PROJROOT)/eurorack/stmlib/third_party/STM
UINCDIR += $(PROJROOT)/eurorack/stmlib/third_party/STM/CMSIS/CM3_f4xx
UINCDIR += $(PROJROOT)/eurorack/stmlib/third_party/STM/STM32F4xx_StdPeriph_Driver/inc

##############################################################################
# Linker options
#
# Export only the drumlogue unit ABI.  Without this every unit exports its
# whole port layer (OSC_CYCLE, osc_adapter_*, the eurorack DSP, ...), and
# since the drumlogue loads all installed units into one address space the
# first unit loaded hijacks the identically-named symbols of every unit
# loaded after it.  See drumlogue/unit_exports.map for the details.

USE_LDOPT = --version-script=$(PROJROOT)/drumlogue/unit_exports.map

##############################################################################
# Libraries
#

ULIBDIR =

ULIBS  = -lm
ULIBS += -lc

##############################################################################
# Defines
#

UDEFS  = -DCLOUDS_FX -DCLOUDS_OPT_ENGINE -DSTM32F401xC -DSTM32F401xx
UDEFS += -DOSC_NATIVE_BLOCK_SIZE=32
UDEFS += -DBLOCKSIZE=32
