// Copyright 2016 Olivier Gillet.
//
// Author: Olivier Gillet (pichenettes@mutable-instruments.net)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// See http://creativecommons.org/licenses/MIT/ for more information.
//
// -----------------------------------------------------------------------------
//
// LPC10 encoded words extracted from various TI ROMs.
//
// -----------------------------------------------------------------------------
//
// FORKED for eurorack-prologue (see eurorack-opt/README.md).
// Forked at submodule commit 58b9125. Changed:
//
//   LPC_SPEECH_SYNTH_NUM_WORD_BANKS raised from 5 to 6.
//
// That constant is the whole reason this file is forked. It sizes the
// word_banks_ array and is the number SpeechEngine::Init hands to
// LPCSpeechSynthWordBank::Init, so a sixth bank cannot be added from
// outside the header: defining word_banks_[6] against an extern
// declaration of [5] is a type error, and the engine would only ever
// look at the first five entries anyway.
//
// Mussola needs six because the Madama Butterfly material now fills four
// banks (Puccini I-IV) alongside the two liturgical ones. The banks
// themselves live in mussola_words.cc, which is generated by
// tools/generate_lpc_words.py and asserts its own count against this one.
//
// The TI-ROM bank_0..bank_4 declarations below are upstream's, and are
// deliberately left as they are: the arrays they name are defined in
// lpc_speech_synth_words.cc, which Mussola does not link (mussola_words.cc
// supplies word_banks_ instead). They are unreferenced declarations, and
// removing them would be a gratuitous divergence from upstream in a file
// whose only intended difference is the count above.
//
// Nothing else in the file is changed. Any unit that wants upstream's five
// TI-ROM banks must not put eurorack-opt/ on its include path ahead of
// eurorack/ -- today only Mussola compiles this header at all.

#ifndef PLAITS_DSP_SPEECH_LPC_SPEECH_SYNTH_WORDS_H_
#define PLAITS_DSP_SPEECH_LPC_SPEECH_SYNTH_WORDS_H_

#include "plaits/dsp/speech/lpc_speech_synth_controller.h"

namespace plaits {

#define LPC_SPEECH_SYNTH_NUM_WORD_BANKS 6

extern const uint8_t bank_0[1233];
extern const uint8_t bank_1[900];
extern const uint8_t bank_2[1552];
extern const uint8_t bank_3[2524];
extern const uint8_t bank_4[4802];

extern LPCSpeechSynthWordBankData word_banks_[LPC_SPEECH_SYNTH_NUM_WORD_BANKS];

}  // namespace plaits

#endif  // PLAITS_DSP_SPEECH_LPC_SPEECH_SYNTH_WORDS_H_
