##############################################################################
# SDK project configuration for mo2_grn
#
# Generated by generate_sdk_projects.sh
# For use with logue-sdk Docker build system.
##############################################################################

PROJECT := mo2_grn
PROJECT_TYPE := synth

# Path back to eurorack-prologue repo root
# (from drumlogue/<project>/ up two levels to repo root)
PROJROOT = ../..

# Override SDK Makefile defaults.
# The SDK Makefile sets COMMON_INC_PATH/COMMON_SRC_PATH with ?= to
# $(realpath $(PROJECT_ROOT)/../common/), expecting common/ as a sibling
# of the project's parent dir.  In our layout the SDK common/ is inside
# the logue-sdk submodule, so that realpath returns empty.  Our unconditional
# = here takes precedence over the ?= in the Makefile.
COMMON_INC_PATH = $(PROJROOT)/logue-sdk/platform/drumlogue/common
COMMON_SRC_PATH = $(PROJROOT)/logue-sdk/platform/drumlogue/common

##############################################################################
# Sources
#

# C sources (unit header)
CSRC = $(PROJROOT)/header.c

# C++ sources (drumlogue wrapper + adapter + oscillator + engine)
CXXSRC  = $(PROJROOT)/drumlogue_unit_wrapper.cc
CXXSRC += $(PROJROOT)/drumlogue_osc_adapter.cc
CXXSRC += $(PROJROOT)/macro-oscillator2.cc
CXXSRC += $(PROJROOT)/eurorack/plaits/dsp/engine/grain_engine.cc
CXXSRC += $(PROJROOT)/eurorack/plaits/resources.cc
CXXSRC += $(PROJROOT)/eurorack/stmlib/dsp/units.cc

##############################################################################
# Include paths
#
# - drumlogue/   : userosc.h compatibility header
# - eurorack/    : Mutable Instruments source headers
# - repo root    : drumlogue_osc_adapter.h
#
# SDK common/ headers (runtime.h, unit.h, attributes.h) are added
# automatically by the SDK Makefile via DINCDIR.
#

UINCDIR  = $(PROJROOT)/drumlogue
UINCDIR += $(PROJROOT)/eurorack
UINCDIR += $(PROJROOT)

##############################################################################
# Libraries
#

ULIBDIR =

ULIBS  = -lm
ULIBS += -lc

##############################################################################
# Defines
#

UDEFS  = -DOSC_GRN
UDEFS += -DOSC_NATIVE_BLOCK_SIZE=24
