##############################################################################
# SDK project configuration for mo2_string
#
# Generated by generate_sdk_projects.sh
# For use with logue-sdk Docker build system.
##############################################################################

PROJECT := mo2_string
PROJECT_TYPE := synth

# Path back to eurorack-prologue repo root
# (from drumlogue/<project>/ up two levels to repo root)
PROJROOT = ../..

# Override SDK Makefile defaults.
# The SDK Makefile sets COMMON_INC_PATH/COMMON_SRC_PATH with ?= to
# $(realpath $(PROJECT_ROOT)/../common/), expecting common/ as a sibling
# of the project's parent dir.  In our layout the SDK common/ is inside
# the logue-sdk submodule, so that realpath returns empty.  Our unconditional
# = here takes precedence over the ?= in the Makefile.
COMMON_INC_PATH = $(PROJROOT)/logue-sdk/platform/drumlogue/common
COMMON_SRC_PATH = $(PROJROOT)/logue-sdk/platform/drumlogue/common

##############################################################################
# Sources
#

# C sources (unit header)
CSRC = $(PROJROOT)/header.c

# C++ sources (drumlogue wrapper + adapter + oscillator + engine)
CXXSRC  = $(PROJROOT)/drumlogue_unit_wrapper.cc
CXXSRC += $(PROJROOT)/drumlogue_osc_adapter.cc
CXXSRC += $(PROJROOT)/macro-oscillator2.cc
CXXSRC += $(PROJROOT)/eurorack/plaits/dsp/engine/string_engine.cc
CXXSRC += $(PROJROOT)/eurorack/plaits/dsp/physical_modelling/string_voice.cc
CXXSRC += $(PROJROOT)/eurorack/plaits/dsp/physical_modelling/string.cc
CXXSRC += $(PROJROOT)/eurorack/plaits/resources.cc
CXXSRC += $(PROJROOT)/eurorack/stmlib/dsp/units.cc
CXXSRC += $(PROJROOT)/eurorack/stmlib/utils/random.cc

##############################################################################
# Include paths
#
# - drumlogue/    : userosc.h compatibility header
# - eurorack-opt/ : forked/optimized MI headers, and so it MUST precede
#                   eurorack/ -- it shadows a few of the submodule's headers
#                   and a build where only some objects see them is corrupt.
#                   Listed for every project, not just the ones forking today,
#                   so the ordering rule holds by construction.
# - eurorack/     : Mutable Instruments source headers
# - repo root     : drumlogue_osc_adapter.h
#
# SDK common/ headers (runtime.h, unit.h, attributes.h) are added
# automatically by the SDK Makefile via DINCDIR.
#

UINCDIR  = $(PROJROOT)/drumlogue
UINCDIR += $(PROJROOT)/eurorack-opt
UINCDIR += $(PROJROOT)/eurorack
UINCDIR += $(PROJROOT)
UINCDIR += $(PROJROOT)/eurorack/stmlib/third_party/STM
UINCDIR += $(PROJROOT)/eurorack/stmlib/third_party/STM/CMSIS/CM3_f4xx
UINCDIR += $(PROJROOT)/eurorack/stmlib/third_party/STM/STM32F4xx_StdPeriph_Driver/inc

##############################################################################
# Linker options
#
# Export only the drumlogue unit ABI.  Without this every unit exports its
# whole port layer (OSC_CYCLE, osc_adapter_*, the eurorack DSP, ...), and
# since the drumlogue loads all installed units into one address space the
# first unit loaded hijacks the identically-named symbols of every unit
# loaded after it.  See drumlogue/unit_exports.map for the details.

USE_LDOPT = --version-script=$(PROJROOT)/drumlogue/unit_exports.map

##############################################################################
# Libraries
#

ULIBDIR =

ULIBS  = -lm
ULIBS += -lc

##############################################################################
# Defines
#

UDEFS  = -DOSC_STRING
UDEFS += -DOSC_NATIVE_BLOCK_SIZE=24
UDEFS += -DBLOCKSIZE=24
